---
dist: bionic
language: generic
env:
    global:
        - use_coveralls=true
        - CONTAINER_CMD=docker
    matrix:
        - CONTAINER_IMAGE=docker.io/nmstate/centos8-nmstate-dev:nmstate-0.2
          testflags="--test-type integ --pytest-args='-x'"
          use_codecov=true
          use_coveralls=false
        - CONTAINER_IMAGE=docker.io/nmstate/centos8-nmstate-dev:nmstate-0.2
          testflags="--test-type integ_slow --pytest-args='-x'"
        - CONTAINER_IMAGE=docker.io/nmstate/centos8-nmstate-dev:nmstate-0.2
          testflags="--test-type integ --pytest-args='-x'
              --copr networkmanager/NetworkManager-1.22-git"
        - CONTAINER_IMAGE=docker.io/nmstate/centos8-nmstate-dev:nmstate-0.2
          testflags="--test-type integ --pytest-args='-x'
              --copr networkmanager/NetworkManager-master"
        - CONTAINER_IMAGE=docker.io/nmstate/centos8-nmstate-dev:nmstate-0.2
          testflags="--test-type format"
        - CONTAINER_IMAGE=docker.io/nmstate/centos8-nmstate-dev:nmstate-0.2
          testflags="--test-type lint"
        - CONTAINER_IMAGE=docker.io/nmstate/centos8-nmstate-dev:nmstate-0.2
          testflags="--test-type unit_py36"
        - testflags="--test-vdsm"

matrix:
    fast_finish: true
    allow_failures:
        - env: CONTAINER_IMAGE=docker.io/nmstate/centos8-nmstate-dev:nmstate-0.2
               testflags="--test-type integ --pytest-args='-x'
                   --copr networkmanager/NetworkManager-1.22-git"
        - env: CONTAINER_IMAGE=docker.io/nmstate/centos8-nmstate-dev:nmstate-0.2
               testflags="--test-type integ --pytest-args='-x'
                   --copr networkmanager/NetworkManager-master"
        - env: testflags="--test-vdsm"

addons:
    apt:
        packages:
            - git
            - gnupg2
            - openssh-client
            - python-tox
            - xz-utils

services:
    - docker

script:
    - sudo modprobe openvswitch
    - sudo ./automation/run-tests.sh $testflags

after_success:
    - sudo pip install coveralls codecov
    - sudo mv .coverage .coverage.orig || true
    - sudo mv tests/.coverage .coverage.tox || true
    - sudo coverage combine --append .
    - test "${use_coveralls}" == "true" && coveralls || true
    - test "${use_codecov}" == "true" && codecov || true

after_failure:
    - sudo ./automation/upload_test_artifacts.sh
